GET http://localhost:5000/user

###

GET http://localhost:5000/login/user/674ae3c72dcf8531f0c82c49

###

POST http://localhost:5000/user
Content-Type: application/json

{
    "userName": "Prince Nwachukwu",
    "email": "princenwachukwu@gmail.com",
    "occupation": "Business Man",
    "password": "prince@32"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "hanson@gmail.com",
    "password": "handson@3"
}

###

PUT http://localhost:5000/login/user/674af502ddb3704e37baf36b
Content-Type: application/json

{
    "userName": "Hanson"
}

###

DELETE  http://localhost:5000/user/674aee3e2dcf8531f0c82c4a
Content-Type: application/json
