GET http://localhost:5000/user

###

GET http://localhost:5000/user/673dc629a091bb83922b0ffd

###

POST http://localhost:5000/user
Content-Type: application/json

{
    "userName": "Handson",
    "email": "hanson@gmail.com",
    "occupation": "student",
    "password": "handson"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "princenwachukwu308@yahoo.com",
    "password": "handson"
}

###

PUT http://localhost:5000/user/673dc345e49f2a9f494a1fa9
Content-Type: application/json

{
    "email": "princenwachukwu308@yahoo.com"
}

###

DELETE  http://localhost:5000/user/673dc29e7b17a69b89ce1438
Content-Type: application/json
